C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\PrezentacionaLogika.deps.json
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\PrezentacionaLogika.runtimeconfig.json
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\PrezentacionaLogika.dll
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\PrezentacionaLogika.pdb
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\DBUtils.dll
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\KlasePodataka.dll
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\KlasePodataka.pdb
C:\Users\Korisnik\source\repos\PrezentacionaLogika\bin\Debug\net8.0\DBUtils.pdb
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.csproj.AssemblyReference.cache
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.GeneratedMSBuildEditorConfig.editorconfig
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.AssemblyInfoInputs.cache
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.AssemblyInfo.cs
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.csproj.CoreCompileInputs.cache
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\Prezenta.34EB9E51.Up2Date
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.dll
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\refint\PrezentacionaLogika.dll
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.pdb
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\PrezentacionaLogika.genruntimeconfig.cache
C:\Users\Korisnik\source\repos\PrezentacionaLogika\obj\Debug\net8.0\ref\PrezentacionaLogika.dll
